language: bash
sudo: required

matrix:
  include:
    - env: flavour=latest
      services:
        - docker
    - env: flavour=alpine
      services:
        - docker
  fast_finish: true

script:
  - if [ "$flavour" = "latest" ]; then make build-latest; else make build-alpine; fi
  - docker run -it --rm jakzal/phpqa:$flavour php /usr/local/bin/tools.php test
  - docker run -it --rm jakzal/phpqa:$flavour

after_script:
  - docker images
