language: bash
sudo: required

services:
  - docker

matrix:
  include:
    - flavour: latest
    - flavour: alpine
  fast_finish: true

script:
  - if [ "$flavour" = "latest" ]; then make build; else make build-alpine; fi
  - docker run -it --rm jakzal/phpqa:$flavour

after_script:
  - docker images
